[package]
name = "ktls-fun"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
ktls = "6.0.1"
rustls = "0.23.15"
tokio = { version = "1.41.0", features = ["full"] }
tokio-rustls = "0.26.0"
webpki-roots = "0.26.6"

[[bin]]
name = "tls"

[[bin]]
name = "ktls"
